language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

sudo: false

env:
  - APP_DEBUG=false

before_script:
- composer install
- cp .env.example .env
- php artisan key:generate

install:
  - composer install --prefer-dist --optmize-autoloader --quiet

script: phpunit -c phpunit.xml --coverage-text