language: php
php:
- 7.1
sudo: true
services:
  - mysql
  - redis-server
env:
  global:
    DB_HOST: 127.0.0.1
    DB_PORT: 3306
    DB_DATABASE: testdatabase
    DB_USERNAME: root
    DB_PASSWORD: password

before_script:
- composer install
- cp .env.example .env
before_install:
- mysql -e "CREATE DATABASE testdatabase DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_unicode_ci;"
- mysql -e "SET PASSWORD = PASSWORD('password');"
install:
- composer install
script:
- composer database
- php vendor/bin/phpcs
- php vendor/bin/phpunit
deploy:
  provider: heroku
  api_key:
    secure: f6HMzVoxEgW6TH79U4riI5P9QlvATieOxZgGYzC0NPuW45NeUEuQFGKhKN1UsLjH5KBKtuKgX4DMEK//XEKEZJMyNXThgYLuKaBmTsUU4rT103xCH7eVYYKWuBI3g2CIDGd4Sx/6SCoQi6YYsFer+35hmUFzjhnLdfxfBYNY5v74/czPvMHG5RmhE3PRXGVu9at72sPsup3bk2+MnADhCudPzu2I3cJmf/f2DDXnWkX7wMumxVQ6+mQcIcZSPZtAwXhdT/lXqg9iny8MNfPUkgUhMbmBQXUw18rzBP1IgLXFYu6Z5KFFYQfgDdUXBMeF0pRxGRheVlV8krTSWlUF7QHdCRwT8vDXBJ1OBNwxH+pG1Pjsy1dOPzIbD7JFYMpTkfDGx/QVe5hp2tCqgcD34302h5OshnSN2uxjn08XbjarvEqJeSoOsjcq02VmG0RMRuaNJP2SqT9tcuNzaaIMFYVd5OJztFjeA9nIJR74ENFYOmyaof8kYP4wnq9PBrnbrRHwjQtQDjhgl9fu+fGxUVeQ4dtOGKR5XogepnsBftci3Mx7QP6bXvnaJSQvJRE1zHGPNELOb76F5Eer0X8LDLK8+WUWy7Lu+CshGgIL3/YCRUNi5zSo4PtzHAtCAvPuMIqQ6I8/h5hLhYI/CFX5tQoKrAzHIaORn/B0VHEdKMM=
  app: php-crawler-chat-bot
  on:
    repo: Tai-ch0802/php-crawler-chat-bot
notifications:
  slack:
    secure: Xrh6ALC+pH7Tsy7mEmoIsNawVdHfJBbQVmOygKrxQBPkSxrYXXokCAQXGDA7R9KD5PbaPy58lOcE2dc/ZCMWX4jkd08z+I1WICT6R5PR0/7wfpmU92G7VW2W2Xd1N4OeVgDCkDepQ0vq8bZ/xafNKDzNboDswNqf+9hGRpli76Mo+ceGjh21Yi0k4kccl1r0mamZCtsn7zBuHOr0kTPhQwNHXcArMusVKxeqb8wWY1DckQJsnN5KXd/ecq2BCVHR9GSyXORXrqX49xe2yG05yAVQayxhLcdhJMK6kXnNjM3NAJmii5Au7tYc6ekR2GJLXldLKjjCRLgnXFL+/dUFFXob7+QVV8hUt5/xeBB0tSnwhNrNu/IgGoXs28eSHUuz8tErf6q4vYT4Cz3INOnERjibxzs7hMmim/KVGO6Q4W2ZOLklHeNNKVKd7rI2uIPiez4B1I6A4V+fCsKd6XC5E6eq/Z7M9dq8meLlxHraB5ksbI6iw1o7vFEy2X2nBh0ZuDe4jT2B8DlMi1UYDZkfPbkDzxCY9uiZTyFI1ddwWnLN8dtUeLhQ7+KqVz6DzGMWofMpUL1VpiQY0KyZlXV6WPT+3Ud2NWJ2G08j9snnmhbbIFDZa0UDwVLSaZ5G3hkX16NHecsDt5GXWbpDavCpVH9w/f9r7eid7aS6ViGxNzk=

