language: php

php:
  - 7.1

sudo: true

env:
  - APP_DEBUG=false

before_script:
- composer install
- cp .env.example .env
- php artisan key:generate

install:
  - composer install

script:
- php vendor/bin/phpunit
