language: php

php:
  - 7.1

sudo: true

env:
  - APP_DEBUG=false

before_script:
- composer install
- cp .env.example .env
- php artisan key:generate

install:
  - composer install

script:
- php vendor/bin/phpcs
- php vendor/bin/phpunit

deploy:
  provider: heroku
  api_key:
    secure: 3dcc61c7-a9ca-4efe-aeb7-8d202a305f55
  run: "php artisan key:generate"
