<?php
namespace Tests\Feature\Services;

use App\Services\LineBotService;
use App\Services\SlackService;
use Tests\TestCase;

class SlackServiceTest extends TestCase
{
    /** @var  slackService */
    private $slackService;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->slackService = app(SlackService::class);
    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testBuildClient()
    {
        $webhook = env('SLACK_WEBHOOK_URL');
        $client = $this->slackService->buildClient($webhook, '#random', 'TestFromLaravel');

        $this->assertEquals('#random', $client->getDefaultChannel());
        $this->assertEquals('TestFromLaravel', $client->getDefaultUsername());
        return $client;
    }

    /**
     * @depends testBuildClient
     */
    public function testSendMessage($client)
    {
        $this->slackService->sendMessage($client, 'test message.');
    }

}
