<?php
namespace Tests\Unit\Services;

use App\Services\BangumiService;
use Tests\TestCase;

class BangumiServiceTest extends TestCase
{
    /** @var  BangumiService */
    private $target;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->target = app(BangumiService::class);
    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testGetCalendar()
    {
        $response = $this->target->getCalendar();

        $this->assertCount(7, $response);
    }

    public function testGetSubjectEps()
    {
        $response = $this->target->getSubjectEps(225631);

        $this->assertSame(225631, $response['id']);
    }
}
