<?php
namespace Tests\Unit\Services;

use App\Services\ComicService;
use App\Services\CrawlerService;
use Tests\TestCase;

class ComicServiceTest extends TestCase
{
    /** @var  ComicService */
    private $comicService;


    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->comicService = app(ComicService::class);
    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testBuildFollowList()
    {
        $response = $this->comicService->buildFollowList();

        $this->assertNotEmpty($response->toArray());
    }

    public function testGetComicName()
    {
        $response = $this->comicService->getComicName('7688');

        $this->assertEquals('監獄學園 (平本彰)', $response);
    }

    public function testShouldReturnNullGetComicName()
    {
        $response = $this->comicService->getComicName('7688abcdefg');

        $this->assertNull($response);
    }
}
