<?php
namespace Tests\Unit\Services;

use App\Services\TwitchService;
use Tests\TestCase;

class TwitchServiceTest extends TestCase
{
    /** @var TwitchService */
    private $twitchService;


    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        if (empty(env('TWITCH_CLIENT_ID'))) {
            $this->markTestSkipped('Invalid TWITCH_CLIENT_ID');
        }
        $this->twitchService = app(TwitchService::class);
    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testGetLiveStreams()
    {
        $response = $this->twitchService->getLiveStreams('nightblue3');
        $this->assertEquals(200, $response->getStatusCode());
    }
}
